name: Build Windows App

on:
  push:
    branches: [ qt ]

permissions:
  contents: write

jobs:
  build:
    name: Build with Nuitka and Upload
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyaudio imageio nuitka argparse requests

      - name: Compile with Nuitka
        run: nuitka Underbridge.py --assume-yes-for-downloads

      - name: List Output Files
        run: dir dist

      - name: Zip the output
        run: python zipit.py dist/Underbridge.dist underbridge-light-win.zip

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: qt
          name: "Underbridge-light Release (qt)"
          draft: false
          prerelease: false
          files: underbridge-light-win.zip

      - name: Upload to Cloud2
        run: |
          python nc_upload.py ${{ secrets.UBRIDGE_USER }} ${{ secrets.UBRIDGE_PASSWD }} `
            https://cloud.raise-uav.com/ `
            underbridge-light-win.zip `
            App_Release/light/underbridge-light-win.zip
