name: Build Linux App

on:
  push:
    branches: [ qt ]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y portaudio19-dev python3-pyaudio patchelf

      - name: Setup Python venv and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip wheel
          pip install -r requirements-linux.txt
          pip install nuitka argparse requests

      - name: Build with Nuitka
        run: |
          source venv/bin/activate
          nuitka underbridge.py --standalone --output-dir=dist --output-filename=Underbridge-light

      - name: Rename output folder
        run: mv dist/Underbridge-light.dist Underbridge-light

      - name: Zip the output
        run: zip -r underbridge-light-linux.zip Underbridge-light

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.2.0
          name: "Underbridge-light Release (qt)"
          draft: false
          prerelease: false
          files: underbridge-light-linux.zip
          body: |
            🎉 **Underbridge-light 1.2.0 Released!**
            
            ✅ Windows Mac M1 and Linux versions now available.
            
            **What's new:**
            - New Interface
            - Fixed number of tracks
            - Improved logic and stability.

      - name: List output files
        run: ls Underbridge-light/

      - name: Upload to Server3
        run: |
          source venv/bin/activate
          python nc_upload.py ${{ secrets.UBRIDGE_USER }} ${{ secrets.UBRIDGE_PASSWD }} https://cloud.raise-uav.com/ underbridge-light-linux.zip App_Release/underbridge-light-linux.zip

