name: Build linux app

on:
  push:
    branches: [ qt ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Use stable Python that matches hosted runner's GLIBC

      - run: sudo apt update
      - run: sudo apt install -y portaudio19-dev python3-pyaudio patchelf

      - run: pip install --upgrade pip wheel
      - run: pip install -r requirements-linux.txt
      - run: pip install nuitka argparse requests

      - name: Build with Nuitka
        run: nuitka underbridge.py

      - run: ls dist/

      - name: Zip the output
        run: python zipit.py dist/Underbridge.dist underbridge-light.zip

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          name: "Underbridge-light Release"
          tag: ${{ github.ref_name }}
          draft: true
          assets: |
            underbridge-light.zip

      - name: Upload to Server
        run: |
          packit/ubridge/bin/python nc_upload.py \
            ${{ secrets.UBRIDGE_USER }} \
            ${{ secrets.UBRIDGE_PASSWD }} \
            https://cloud.raise-uav.com/ \
            underbridge-light.zip \
            App_Release/light/underbridge-light-linux.zip
