name: Build Windows App

on:
  push:
    branches: [ qt ]

permissions:
  contents: write

jobs:
  build:
    name: Build with Nuitka and Upload
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Setup Python virtual environment and install dependencies
        shell: pwsh
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements-windows.txt
          pip install pyaudio imageio nuitka argparse requests

      - name: Compile with Nuitka in venv
        shell: pwsh
        run: |
          .\venv\Scripts\Activate.ps1
          nuitka Underbridge.py --standalone --assume-yes-for-downloads --output-dir=dist --output-filename=Underbridge-light

      - name: List Output Files
        run: dir dist

      - name: Rename output folder
        shell: pwsh
        run: |
          Rename-Item -Path 'dist\\Underbridge-light.dist' -NewName 'Underbridge-light'

      - name: Zip the folder (include top-level directory)
        shell: pwsh
        run: |
          Compress-Archive -Path 'dist\\Underbridge-light' -DestinationPath 'underbridge-light-win.zip'

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.2.0
          name: "Underbridge-light Release (qt)"
          draft: false
          prerelease: false
          files: underbridge-light-win.zip
          body: |
            🎉 **Underbridge-light 1.2.0 Released!**
            
            ✅ Windows Mac M1 and Linux versions now available.
            
            **What's new:**
            - New Interface
            - Fixed number of tracks
            - Improved logic and stability.

      #- name: Upload to Cloud2
      #  shell: pwsh
      #  run: |
      #    python nc_upload.py ${{ secrets.UBRIDGE_USER }} ${{ secrets.UBRIDGE_PASSWD }} https://cloud.raise-uav.com/ underbridge-light-win.zip App_Release/underbridge-light-win.zip"""

